import type { FruitData } from "./types";
export const rarityColor = {
  common: "border-gray-500",
  uncommon: "border-blue-600",
  rare: "border-purple-500",
  legendary: "border-pink-600",
  mythical: "border-red-500",
};
export const blox = [
  { name: "Rocket", rarity: "common", chance: 130 },
  { name: "Spin", rarity: "common", chance: 130 },
  { name: "Chop", rarity: "common", chance: 150 },
  { name: "Spring", rarity: "common", chance: 140 },
  { name: "Bomb", rarity: "common", chance: 140 },
  { name: "Smoke", rarity: "common", chance: 130 },
  { name: "Spike", rarity: "common", chance: 150 },
  { name: "Flame", rarity: "uncommon", chance: 120 },
  { name: "Falcon", rarity: "uncommon", chance: 150 },
  { name: "Ice", rarity: "uncommon", chance: 140 },
  { name: "Sand", rarity: "uncommon", chance: 70 },
  { name: "Dark", rarity: "uncommon", chance: 85 },
  { name: "Diamond", rarity: "uncommon", chance: 80 },
  { name: "Light", rarity: "rare", chance: 110 },
  { name: "Rubber", rarity: "rare", chance: 71 },
  { name: "Barrier", rarity: "rare", chance: 78 },
  { name: "Ghost", rarity: "rare", chance: 79 },
  { name: "Magma", rarity: "rare", chance: 73 },
  { name: "Quake", rarity: "legendary", chance: 64 },
  { name: "Buddha", rarity: "legendary", chance: 66 },
  { name: "Love", rarity: "legendary", chance: 77 },
  { name: "Spider", rarity: "legendary", chance: 57 },
  { name: "Sound", rarity: "legendary", chance: 51 },
  { name: "Phoenix", rarity: "legendary", chance: 35 },
  { name: "Portal", rarity: "legendary", chance: 68 },
  { name: "Rumble", rarity: "legendary", chance: 23 },
  { name: "Pain", rarity: "legendary", chance: 28 },
  { name: "Blizzard", rarity: "legendary", chance: 13 },
  { name: "Gravity", rarity: "mythical", chance: 15 },
  { name: "Mammoth", rarity: "mythical", chance: 12 },
  { name: "T-Rex", rarity: "mythical", chance: 14 },
  { name: "Dough", rarity: "mythical", chance: 13 },
  { name: "Shadow", rarity: "mythical", chance: 11 },
  { name: "Venom", rarity: "mythical", chance: 10 },
  { name: "Control", rarity: "mythical", chance: 18 },
  { name: "Spirit", rarity: "mythical", chance: 8 },
  { name: "Dragon", rarity: "mythical", chance: 7 },
  { name: "Leopard", rarity: "mythical", chance: 3 },
  { name: "Kitsune", rarity: "mythical", chance: 81 },
] as FruitData[];
