import type { FruitData } from "./types";
export const rarityColor = {
  common: "border-gray-500 divide-gray-500",
  uncommon: "border-blue-600 divide-blue-600",
  rare: "border-purple-500 divide-purple-500",
  epic: "border-orange-500 divide-orange-500",
  legendary: "border-pink-600 divide-pink-600",
  mythical: "border-red-500 divide-red-500",
};

export const blox = [
  { name: "Rocket", rarity: "common", chance: 140 },
  { name: "Spin", rarity: "common", chance: 150 },
  { name: "Blade", rarity: "common", chance: 130 },
  { name: "Spring", rarity: "common", chance: 140 },
  { name: "Bomb", rarity: "common", chance: 140 },
  { name: "Smoke", rarity: "common", chance: 130 },
  { name: "Spike", rarity: "common", chance: 140 },
  { name: "Flame", rarity: "uncommon", chance: 120 },
  { name: "Falcon", rarity: "uncommon", chance: 135 },
  { name: "Ice", rarity: "uncommon", chance: 120 },
  { name: "Sand", rarity: "uncommon", chance: 92 },
  { name: "Dark", rarity: "uncommon", chance: 89 },
  { name: "Diamond", rarity: "uncommon", chance: 100 },
  { name: "Light", rarity: "rare", chance: 85 },
  { name: "Rubber", rarity: "rare", chance: 90 },
  { name: "Barrier", rarity: "rare", chance: 90 },
  { name: "Ghost", rarity: "rare", chance: 79 },
  { name: "Magma", rarity: "rare", chance: 70 },
  { name: "Quake", rarity: "legendary", chance: 64 },
  { name: "Buddha", rarity: "legendary", chance: 48 },
  { name: "Love", rarity: "legendary", chance: 55 },
  { name: "Spider", rarity: "legendary", chance: 56 },
  { name: "Sound", rarity: "legendary", chance: 45 },
  { name: "Phoenix", rarity: "legendary", chance: 50 },
  { name: "Portal", rarity: "legendary", chance: 40 },
  { name: "Rumble", rarity: "legendary", chance: 25 },
  { name: "Pain", rarity: "legendary", chance: 48 },
  { name: "Blizzard", rarity: "legendary", chance: 20 },
  { name: "Gravity", rarity: "mythical", chance: 15 },
  { name: "Mammoth", rarity: "mythical", chance: 11 },
  { name: "T-Rex", rarity: "mythical", chance: 12 },
  { name: "Dough", rarity: "mythical", chance: 10 },
  { name: "Shadow", rarity: "mythical", chance: 13 },
  { name: "Venom", rarity: "mythical", chance: 10 },
  { name: "Control", rarity: "mythical", chance: 15 },
  { name: "Gas", rarity: "mythical", chance: 7 },
  { name: "Spirit", rarity: "mythical", chance: 8 },
  { name: "Leopard", rarity: "mythical", chance: 5 },
  { name: "Yeti", rarity: "mythical", chance: 4 },
  { name: "Kitsune", rarity: "mythical", chance: 3 },
  {
    name: "Dragon (West)",
    rarity: "mythical",
    chance: 2,
    img: "Dragon_(West)Fruit.webp",
  },
  {
    name: "Dragon (East)",
    rarity: "mythical",
    chance: 1,
    img: "Dragon_(East)Fruit.webp",
  },
] as FruitData[];

export const battleground: FruitData[] = [
  // Common Fruits
  { name: "Barrier", rarity: "common", chance: 2110 },
  { name: "Chop", rarity: "common", chance: 2110 },
  { name: "Sand", rarity: "common", chance: 2110 },
  // Uncommon Fruits
  { name: "Smoke", rarity: "uncommon", chance: 807 },
  { name: "Rubber", rarity: "uncommon", chance: 605 },
  { name: "Falcon", rarity: "uncommon", chance: 573 },
  { name: "Gas", rarity: "uncommon", chance: 595 },
  // Rare Fruits
  { name: "Bomb", rarity: "rare", chance: 233 },
  { name: "Ice", rarity: "rare", chance: 149 },
  { name: "Darkness", rarity: "rare", chance: 138 },
  { name: "Ash", rarity: "rare", chance: 104 },
  // Epic Fruits
  { name: "Light", rarity: "epic", chance: 106 },
  { name: "Flame", rarity: "epic", chance: 85 },
  { name: "Magma", rarity: "epic", chance: 59 },
  { name: "Paw", rarity: "epic", chance: 76 },
  { name: "String", rarity: "epic", chance: 68 },
  { name: "Love", rarity: "epic", chance: 59 },
  // Legendary Fruits
  { name: "Quake", rarity: "legendary", chance: 17 },
  { name: "Gravity", rarity: "legendary", chance: 14 },
  { name: "Phoenix", rarity: "legendary", chance: 12 },
  { name: "Dragon", rarity: "legendary", chance: 5 },
  { name: "TSRubber", rarity: "legendary", chance: 10 },
  { name: "Magnet", rarity: "legendary", chance: 15 },
  { name: "IceV2", rarity: "legendary", chance: 14 },
  { name: "MagmaV2", rarity: "legendary", chance: 14 },
  { name: "LightV2", rarity: "legendary", chance: 15 },
  { name: "FlameV2", rarity: "legendary", chance: 14 },
  { name: "Venom", rarity: "legendary", chance: 7 },
  { name: "Dough", rarity: "legendary", chance: 10 },
  // Mythical Fruits
  { name: "DoughV2", rarity: "mythical", chance: 3 },
  { name: "Leopard", rarity: "mythical", chance: 2 },
  { name: "Ope", rarity: "mythical", chance: 2 },
  { name: "Lightning", rarity: "mythical", chance: 3 },
  { name: "Nika", rarity: "mythical", chance: 1 },
  { name: "DragonV2", rarity: "mythical", chance: 1 },
  { name: "Soul", rarity: "mythical", chance: 1 },
  { name: "DarkXQuake", rarity: "mythical", chance: 1 },
  { name: "Okuchi", rarity: "mythical", chance: 1 },
];
